// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
public abstract class Singleton<T> where T: class,new()
{
	private static readonly object syslock = new object(); 
	private static T _instance = default(T);
	public static T GetSingleton()
	{
		lock (syslock) {
			if (_instance == null) {
				_instance = new T ();
			}
		}
		return _instance;
	}
	
	public virtual void Init(Action callback = null)
	{
		if (callback != null) {
			callback();
		}
	}
	public virtual void Dispose()
	{
	}
}


