// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using System;
public abstract class SingletonMono<T>: MonoBehaviour where T : MonoBehaviour
{
	private static readonly object syslock = new object ();
	private static T _instance = default(T);
	public static T GetSingleton()
	{
		lock (syslock) {
			if (_instance == null) {
				T[] objects = FindObjectsOfType<T>();
				if (objects.Length>0){
					_instance = objects[0];
					if(objects.Length>1){
						for(int i=1;i<objects.Length;++i)
						{
							DestroyImmediate(objects[i].gameObject);
						}
					}
					return _instance;
				}
				GameObject go = new GameObject();
				go.name = typeof(T).ToString()+"(Singleton)";
				_instance = go.AddComponent<T>();
				if (Application.isPlaying) {
					DontDestroyOnLoad (go);
				}
			}
		}
		return _instance;
	}
	public virtual void Dispose()
	{
		if (gameObject != null) {
			Destroy(gameObject);
		}
	}
}


